// Code generated by MockGen. DO NOT EDIT.
// Source: covalyzer.go
//
// Generated by this command:
//
//	mockgen -source=covalyzer.go -destination=covalyzer.go_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	reflect "reflect"

	v1 "github.com/nokamoto/covalyzer-go/pkg/api/v1"
	gomock "go.uber.org/mock/gomock"
)

// Mockgh is a mock of gh interface.
type Mockgh struct {
	ctrl     *gomock.Controller
	recorder *MockghMockRecorder
}

// MockghMockRecorder is the mock recorder for Mockgh.
type MockghMockRecorder struct {
	mock *Mockgh
}

// NewMockgh creates a new mock instance.
func NewMockgh(ctrl *gomock.Controller) *Mockgh {
	mock := &Mockgh{ctrl: ctrl}
	mock.recorder = &MockghMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockgh) EXPECT() *MockghMockRecorder {
	return m.recorder
}

// Clone mocks base method.
func (m *Mockgh) Clone(arg0 *v1.Repository) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockghMockRecorder) Clone(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*Mockgh)(nil).Clone), arg0)
}
